Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,9 +28,17 @@ jobs:
         CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
       run: |
         npm install -g wrangler
-        wrangler kv:namespace create KV_STATUS_PAGE || true
-        export KV_NAMESPACE_ID=$(wrangler kv:namespace list | node -pe "JSON.parse(fs.readFileSync('/dev/stdin', 'utf8')).find(kv => kv.title.includes('KV_STATUS_PAGE')).id")
+        wrangler kv namespace create KV_STATUS_PAGE --env production || true
+        wrangler kv namespace list --json > kv_list.json
+        cat kv_list.json
+        export KV_NAMESPACE_ID=$(node -pe "const list=JSON.parse(fs.readFileSync('kv_list.json'));const item=list.find(x=>x.title.includes('KV_STATUS_PAGE'));item?item.id:''")
+        echo "KV_NAMESPACE_ID = >${KV_NAMESPACE_ID}<"
+        if [ -z "$KV_NAMESPACE_ID" ];then
+          echo "ERROR: KV_NAMESPACE_ID 为空，获取KV命名空间失败"
+          exit 1
+        fi
         sed -i 's/KV_ID_PLACEHOLDER/'"${KV_NAMESPACE_ID}"'/g' wrangler.toml
+        cat wrangler.toml
         [ -z "$SECRET_SLACK_WEBHOOK_URL" ] && SECRET_SLACK_WEBHOOK_URL="default-gh-action-secret" || true
         [ -z "$SECRET_TELEGRAM_API_TOKEN" ] && SECRET_TELEGRAM_API_TOKEN="default-gh-action-secret" || true
         [ -z "$SECRET_TELEGRAM_CHAT_ID" ] && SECRET_TELEGRAM_CHAT_ID="default-gh-action-secret" || true
